services:
  - type: web
    name: react-auth-flow-craft
    env: static
    buildCommand: bun install && bun run build && ln -sf dist build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html